version: "3.3"
services:
  spoon:
    image: php:5.6-apache
    container_name: spoon
    entrypoint: "sh -c 'docker-php-ext-install mysqli && apache2-foreground'"
    depends_on:
      - db
    ports:
      - "8787:80"
    volumes:
      - "./spoon-punbb:/var/www/html"
    environment:
      PUID: 995
      PGID: 995
  db:
    image: mysql:5.6
    container_name: spoon-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=spoon
      - MYSQL_USER=sp00n
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
